### ISSUE TITLE
trigger coin fetch from exchange by using cron job

### ISSUE THREAD

**Issue by nateshmbhat** [coinratecap/Backend#62]
create a cron job which auto fetches the prices of coins from exchange at regular intervals so that manually triggering the price fetching by the `trigger` route is not required.

**Comment by Francaolisa** [comment]
No description?

**Comment by nateshmbhat** [comment]
@Francaolisa updated description

**Comment by melodyogonna** [comment]
Ah! I just realized a comment I made with my phone wasn't posted.

I have created a function to schedule and run the cron jobs every N seconds but it might need some more work since I have not clearly seen the signature of the coin-listing functions.

I have just added the ```fetchAllCoinsDataFromExchangesToDb ``` to the cron, the code is at src/app.js.

**Comment by nateshmbhat** [comment]
Please review the PR #65
